### ISSUE TITLE
Local storage input model

### ISSUE THREAD

**Issue by serhii-chernenko** [serhii-chernenko/mentoring-ivan#16]
- [x] Create an input with a value by default "Default Value".
- [x] Then, during editing, you have to save any changes to Local Storage.
- [x] When a page is reloaded, the changes has to be visible in the input instead of "Default Value".
- [x] When the message is edited directly from the browser's DevTools in the "Application" tab, the changes have to be visible in the input immediately
- [x] Create a new `<h1>` tag where the mentioned message has to be a title and changed on every update in input/local storage.

**Comment by kondzerau-ivan** [comment]
> - [ ] Create an input with a value by default "Default Value".
> - [ ] Then, during editing, you have to save any changes to Local Storage.
> - [ ] When a page is reloaded, the changes has to be visible in the input instead of "Default Value".
> - [ ] When the message is edited directly from the browser's DevTools in the "Application" tab, the changes have to be visible in the input immediately
> - [ ] Create a new `<h1>` tag where the mentioned message has to be a title and changed on every update in input/local storage.

Should I create some html file and add input into it?

**Comment by serhii-chernenko** [comment]
> > * [ ]  Create an input with a value by default "Default Value".
> > * [ ]  Then, during editing, you have to save any changes to Local Storage.
> > * [ ]  When a page is reloaded, the changes has to be visible in the input instead of "Default Value".
> > * [ ]  When the message is edited directly from the browser's DevTools in the "Application" tab, the changes have to be visible in the input immediately
> > * [ ]  Create a new `<h1>` tag where the mentioned message has to be a title and changed on every update in input/local storage.
> 
> Should I create some html file and add input into it?

yes. another option is creating a new project with the VanillaJS template in the https://stackblitz.com/ service.

**Comment by serhii-chernenko** [comment]
@kondzerau-ivan hey man, how's it going? Reach me out if you stuck and need help

**Comment by kondzerau-ivan** [comment]
> @kondzerau-ivan hey man, how's it going? Reach me out if you stuck and need help

Sorry. I'm overburdened on my current work. And thank you for your comment, it's raises my motivation.

[Here is the link to stackblitz project.
](https://stackblitz.com/edit/vitejs-vite-gaxiwuij?file=src%2Fmain.js)

**Comment by serhii-chernenko** [comment]
@kondzerau-ivan nice work! the code style and the solution are pretty good!

the only one thing, you use the local storage key hard-coded in 3 places. it'd be better to move the name to a constant variable to simply reuse it. but it's not critical. good work at all!
